language: r
sudo: false
cache: packages
warnings_are_errors: false
service: mysql

r_binary_packages:
  - devtools
  - roxygen2

r_packages:
  - dbplyr

before_script:
  - Rscript -e "install.packages('dbplyr')" 
  - Rscript -e "library(dplyr); summarise(group_by(iris, Species), pl = sum(Petal.Length))"
  - Rscript -e "dplyr::check_dbplyr(); dbplyr::translate_sql(x +1)"
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "CREATE USER 'R'@'localhost' IDENTIFIED BY 'supersecret';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'R'@'localhost';" -uroot
  - printf "[rs-dbi]\nuser=R\nhost = localhost\npassword=supersecret\n" > ~/.my.cnf
  - printf "[client]\nuser = R\nhost = localhost\npassword = supersecret\n" >> ~/.my.cnf

after_success:
  - cat ~/.my.cnf
  - mysql -u root -e "show status"
  - mysql -e "connect test;show tables;" -u R -psupersecret
  - mysql -e "connect test;show tables;"
  - Rscript -e 'devtools::install();devtools::test()'

