language: r
sudo: false
cache: packages
warnings_are_errors: false
service: mysql

r_binary_packages:
  - devtools
  - roxygen2

r_packages:
  - dbplyr

before_script:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "CREATE USER 'R'@'localhost' IDENTIFIED BY 'supersecret';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'R'@'localhost';" -uroot
  - printf "[rs-dbi]\nuser=R\nhost = localhost\npassword=supersecret\n" > ~/.my.cnf
  - printf "[client]\nuser = R\nhost = localhost\npassword = supersecret\n" >> ~/.my.cnf

after_success:
  - Rscript -e 'devtools::install();devtools::test()'
