language: r
sudo: false
cache: packages
warnings_are_errors: false
service: mysql

before_script:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "CREATE USER 'R'@'localhost' IDENTIFIED BY 'supersecret';" -uroot
  - printf "[rs-dbi]\nusername=R\npassword=supersecret\n" > ~/.my.cnf
